### ISSUE TITLE
Split fluid templates into (multiple) partials to make overriding parts easier/granular 

### ISSUE THREAD

**Issue by josefglatz** [sup7even/supi#1]
I had a case where the LLL string `banner.content.text` needs more arguments for `{f:translate()}`.

Splitting up specific parts of the actual FLUID templates/partials/layouts would make modifications less exciting if there are extension updates.

**Comment by garfieldius** [comment]
Implemented by @vkemeter in #9faac5448c3c896daf36de20cdba0fa07d3bbf2a
